package com.hamza.performanceportal.performance.repository;

import com.hamza.performanceportal.performance.entity.Report;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for Report entity
 */
@Repository
public interface ReportRepository extends JpaRepository<Report, Long> {

    /**
     * Find all reports for a specific test run
     */
    List<Report> findByTestRunId(Long testRunId);

    /**
     * Find reports by test run ID and report type
     */
    List<Report> findByTestRunIdAndReportType(Long testRunId, Report.ReportType reportType);

    /**
     * Find all reports of a specific type
     */
    List<Report> findByReportType(Report.ReportType reportType);

    /**
     * Find reports generated by a specific user
     */
    List<Report> findByGeneratedBy(String generatedBy);

    /**
     * Find reports generated within a date range
     */
    @Query("SELECT r FROM Report r WHERE r.generatedAt BETWEEN :startDate AND :endDate")
    List<Report> findByGeneratedAtBetween(
            @Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate);

    /**
     * Find the latest report for a test run
     */
    @Query("SELECT r FROM Report r WHERE r.testRun.id = :testRunId ORDER BY r.generatedAt DESC")
    Optional<Report> findLatestByTestRunId(@Param("testRunId") Long testRunId);

    /**
     * Find the latest report of a specific type for a test run
     */
    @Query("SELECT r FROM Report r WHERE r.testRun.id = :testRunId AND r.reportType = :reportType ORDER BY r.generatedAt DESC")
    Optional<Report> findLatestByTestRunIdAndReportType(
            @Param("testRunId") Long testRunId,
            @Param("reportType") Report.ReportType reportType);

    /**
     * Check if a report exists for a test run
     */
    boolean existsByTestRunId(Long testRunId);

    /**
     * Count reports by type
     */
    long countByReportType(Report.ReportType reportType);

    /**
     * Count reports for a test run
     */
    long countByTestRunId(Long testRunId);

    /**
     * Get total file size for all reports
     */
    @Query("SELECT SUM(r.fileSize) FROM Report r")
    Long getTotalReportsFileSize();

    /**
     * Get total file size for reports of a specific type
     */
    @Query("SELECT SUM(r.fileSize) FROM Report r WHERE r.reportType = :reportType")
    Long getTotalFileSizeByReportType(@Param("reportType") Report.ReportType reportType);

    /**
     * Delete all reports for a test run
     */
    void deleteByTestRunId(Long testRunId);

    /**
     * Find reports older than a specific date (for cleanup)
     */
    @Query("SELECT r FROM Report r WHERE r.generatedAt < :date")
    List<Report> findReportsOlderThan(@Param("date") LocalDateTime date);

    /**
     * Find reports by file name pattern
     */
    @Query("SELECT r FROM Report r WHERE r.fileName LIKE %:pattern%")
    List<Report> findByFileNameContaining(@Param("pattern") String pattern);
}

// Made with Bob